### ISSUE TITLE
VS Code gives me this Error: Error: connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by iMikeT** [barenddt/paladins-api-node#3]
I have installed the Jupyter extension by Don Jayamanne and then I installed Jupyter by using:
pip3 install jupyter

It works and I can use my cmd to type: jupyter notebook and it opens my browser and stuff. But I want to be able to use the extension so the when I do Ctrl+Alt+p I get the search and when you search jupyter you can choose run line and then start new notebook but it then gives me this error:
(Error: connect ECONNREFUSED 127.0.0.1:80
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14))

Please help! I want to be able to do what is done at this link: https://donjayamanne.github.io/pythonVSCodeDocs/docs/jupyter_getting-started/

**Comment by xkisu** [comment]
The author made a mistake in the README, you need to provide the platform in each call as well (PC, XBOX, PS4):

```
pal.connect('PC', (err, res) => {
    if (!err) {
        sessionId = res;
        pal.getPlayer(sessionId, 'PC', 'alayxz', (err, res) => {
            console.log(res);
        });
    };
});
```
